### ISSUE TITLE
Default config seems to be for a multicore pi 1

### ISSUE THREAD

**Issue by Baggypants** [rsta2/minisynth#2]
`configure` seems to write 

`echo "DEFINE += -DARM_ALLOW_MULTI_CORE -DSAVE_VFP_REGS_ON_IRQ" >> Config.mk`

even if you pass 1 for the rpi version. This leads to a compilation error later on.

```
In file included from logger.cpp:24:
../include/circle/multicore.h: In static member function 'static unsigned int CMultiCoreSupport::ThisCore()':
../include/circle/multicore.h:71:20: error: 'CORES' was not declared in this scope
   71 |   return nMPIDR & (CORES-1);
      |                    ^~~~~
```

removing `-DARM_ALLOW_MULTI_CORE` allows the compilation to continue.

**Comment by Baggypants** [comment]
Oh I guess it would help if I checked out a the v2.0 tag

**Comment by rsta2** [comment]
This was an issue in the latest development version. I've corrected it.

**Comment by Baggypants** [comment]
Seems to be fixed, but I can't clean compile because of the issues I'm having in #3

**Comment by Baggypants** [comment]
Confirmed fixed.

**Comment by rsta2** [comment]
Thanks. Because the issue was in a development version, we do not need to wait for the next release and can close this issue.
