### ISSUE TITLE
make: *** No rule to make target 'gnu/stubs-lp64.h', needed by 'lvgl.o'.  Stop.

### ISSUE THREAD

**Issue by styro2000** [rsta2/minisynth#21]
Hello,
after a long pause i am on playing again with the circle framework and wanted to make the minisynth step 44.5
everything compiles but of some problem with lvgl, see the title of the issue...
the configuration is done with: 
./configure 4 /home/styro/gcc-arm-10.3-2021.07-x86_64-aarch64_be-none-linux-gnu/bin/aarch64_be-none-linux-gnu- 64
the host os is Kubutu 22.04.01

many thanks for some help!
all the best
styro

**Comment by rsta2** [comment]
The recommended toolchain to build MiniSynth Pi as 64-bit applications can be downloaded [here](https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads). MiniSynth Pi has been tested with the version *11.3.Rel1* (arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-elf.tar.xz) from this website. Can you please try this toolchain? It requires no special installation, just download and extract the archive to some directory.

**Comment by styro2000** [comment]
Many thanks! that was it!

**Comment by rsta2** [comment]
OK great. You are welcome.
