### ISSUE TITLE
Run on standard raspberry os

### ISSUE THREAD

**Issue by grbfst** [rsta2/minisynth#27]
Hi,
Is there a way to run the minisynth on a standard raspberry install? 
I want to run a python program to receive touch through a capacative sensor to make a standalone touch instrument .

**Comment by rsta2** [comment]
No, MiniSynth Pi does not run on Raspberry Pi OS. It needs the Circle bare-
metal environment.

**Comment by rsta2** [comment]
Question answered, so this can be closed.
